spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Appli_banking
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql  #plus d'inforamtion
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # dialect langage pour pouvoir communique avec db
